# Results from Automated Metrics

In [37]:
# SET UP
import pandas as pd
from datetime import datetime
from notebook_to_lib_config import set_path 
config = set_path()
POST_METRICS_CSV = config["POST_METRICS_PATH"]
M_INTITAL_EXTRACT = config["M_INTITAL_EXTRACT"]
CLEANED_DATA_PATH = config["CLEANED_DATA_PATH"]

In [38]:
post_metrics = pd.read_csv(POST_METRICS_CSV)
length = len(post_metrics)
print(f"{length} rows of data pulled from Instagram Graph API:")
post_metrics.tail()

2845 rows of data pulled from Instagram Graph API:

,name,period,title,description,id,value,datetime_insights_pulled
2840,reach,lifetime,Accounts reached,The number of unique accounts that have seen t...,18171757609292289,2222,2025-03-10 23:39:20
2841,saved,lifetime,Saved,The number of saves of your reel.,18171757609292289,5,2025-03-10 23:39:20
2842,shares,lifetime,Shares,The number of shares of your reel.,18171757609292289,5,2025-03-10 23:39:20
2843,total_interactions,lifetime,Reels interactions,"The number of likes, saves, comments and share...",18171757609292289,113,2025-03-10 23:39:20
2844,views,lifetime,Views,The number of times your reels was played or d...,18171757609292289,2079,2025-03-10 23:39:20

In [33]:
post_metrics['Post ID'] = post_metrics['id']
intital_extract = pd.read_csv(M_INTITAL_EXTRACT)
merged_df = pd.merge(post_metrics, intital_extract, on='Post ID', how='left')
print("Data merged with initial extract: ")
merged_df.head()

Data merged with initial extract:

,name,period,title,description,id,value,datetime_insights_pulled,insights_pulled_date_only,Post ID,Account ID,...,Data comment,Date,Reach,Likes,Shares,Comments,Saves,Follows,datetime_extracted,Views
0,comments,lifetime,Comments,The number of comments on your reel.,18013117540740395,1,2025-03-07 15:16:23,2025-03-07,18013117540740395,17841461458191255,...,NaN,Lifetime,910,64,1,1,3,5.0,2025-03-03 10:38:30.680238,NaN
1,ig_reels_avg_watch_time,lifetime,Reels Average Watch Time (milliseconds),This body communicates the definition for reel...,18013117540740395,6747,2025-03-07 15:16:23,2025-03-07,18013117540740395,17841461458191255,...,NaN,Lifetime,910,64,1,1,3,5.0,2025-03-03 10:38:30.680238,NaN
2,ig_reels_video_view_total_time,lifetime,Video View Total Time (milliseconds),This body communicates the definition for reel...,18013117540740395,6639898,2025-03-07 15:16:23,2025-03-07,18013117540740395,17841461458191255,...,NaN,Lifetime,910,64,1,1,3,5.0,2025-03-03 10:38:30.680238,NaN
3,likes,lifetime,Likes,The number of likes on your reel.,18013117540740395,64,2025-03-07 15:16:23,2025-03-07,18013117540740395,17841461458191255,...,NaN,Lifetime,910,64,1,1,3,5.0,2025-03-03 10:38:30.680238,NaN
4,reach,lifetime,Accounts reached,The number of unique accounts that have seen t...,18013117540740395,926,2025-03-07 15:16:23,2025-03-07,18013117540740395,17841461458191255,...,NaN,Lifetime,910,64,1,1,3,5.0,2025-03-03 10:38:30.680238,NaN

In [36]:
merged_df.columns

Index(['name', 'period', 'title', 'description', 'id', 'value',
       'datetime_insights_pulled', 'insights_pulled_date_only', 'Post ID',
       'Account ID', 'Account username', 'Account name', 'Description',
       'Duration (sec)', 'Publish time', 'Permalink', 'Post type',
       'Data comment', 'Date', 'Reach', 'Likes', 'Shares', 'Comments', 'Saves',
       'Follows', 'datetime_extracted', 'Views'],
      dtype='object')

In [34]:
length = len(merged_df['Post ID'].value_counts())
print(f"Number of posts gathered: {length}")
print(merged_df['Post type'].value_counts())

Number of posts gathered: 145
Post type
IG image       1300
IG carousel    1050
IG reel         477
Name: count, dtype: int64

In [35]:
# Export to Excel
merged_df.to_csv(CLEANED_DATA_PATH + "daily_post_metrics.csv", index=False) 
merged_df.to_excel(CLEANED_DATA_PATH + "daily_post_metrics.xlsx", sheet_name="post_metrics", index=False)